- README.md
Prevents issues like #15 from happening again
> Add note in README about renaming to dry-cli

- lib/hanami/console/plugins/slice_readers.rb
> Fix SliceReaders for new SliceName class

- lib/hanami/cli/commands/application.rb
- lib/hanami/cli/commands/application/server.rb
- lib/hanami/cli/server.rb
- spec/fixtures/test/config.ru
- spec/unit/hanami/cli/commands/application/server_spec.rb
- spec/unit/hanami/cli/server_spec.rb
* Register `hanami server` command
* Make Rubocop happy
---
Follow up of https://github.com/hanami/cli/pull/22
> Register `hanami server` command

- Gemfile
We can do it now that hanami/hanami#1183 has been merged
> Restore depending on hanami#main in the Gemfile

- lib/hanami/console/context.rb
It just replaces the current process with a new execution of the command
> Introduce reload command in the console context

- Gemfile
- hanami-cli.gemspec
- lib/hanami/cli/generators/app/action.rb
- lib/hanami/cli/generators/app/slice.rb
- lib/hanami/cli/generators/gem/app/routes.erb
- spec/unit/hanami/cli/commands/app/generate/action_spec.rb
- spec/unit/hanami/cli/commands/app/generate/slice_spec.rb
- spec/unit/hanami/cli/commands/gem/new_spec.rb
Follow up after hanami/hanami#1208 was merged
> Remove `define do..` from routes

- exe/hanami
- lib/hanami/cli/errors.rb
- lib/hanami/cli/generators/app/action.rb
- spec/integration/run_spec.rb
- spec/unit/hanami/cli/commands/app/generate/action_spec.rb
Don't print stack trace to stderr.
---
Manual tested:
```shell
⚡ bundle exec hanami generate action users.index --slice=foo
slice `foo' is missing, please generate with `hanami generate slice foo'
⚡ echo $?
1
```
---
https://trello.com/c/rtZynx28
> In case of exception, print error message and exit

- lib/hanami/cli/bundler.rb
- lib/hanami/cli/commands/app/generate/action.rb
- lib/hanami/cli/commands/app/generate/slice.rb
- lib/hanami/cli/commands/db/utils/database.rb
- lib/hanami/cli/commands/db/utils/mysql.rb
- lib/hanami/cli/commands/db/utils/postgres.rb
- lib/hanami/cli/commands/db/utils/sqlite.rb
- lib/hanami/cli/commands/gem/new.rb
- lib/hanami/cli/errors.rb
- lib/hanami/cli/generators/app/action.rb
- lib/hanami/cli/repl/core.rb
- lib/hanami/cli/url.rb
- spec/unit/hanami/cli/commands/app/generate/action_spec.rb
- spec/unit/hanami/cli/commands/app/generate/slice_spec.rb
Follow up of https://github.com/hanami/cli/pull/63
---
https://trello.com/c/kY25Cgcm
> Ensure to raise `Hanami::Error` exceptions in case of error

- Gemfile
- lib/hanami/cli/commands/app/command.rb
- lib/hanami/cli/commands/app/server.rb
- lib/hanami/cli/generators/gem/app/puma.erb
- spec/integration/hanami/cli/commands/app/server_spec.rb
- spec/unit/hanami/cli/commands/app/command_spec.rb
- spec/unit/hanami/cli/commands/app/server_spec.rb
Fixes https://github.com/hanami/hanami/issues/1264
Ref https://github.com/hanami/hanami/pull/1266
> Load dotenv and use hanami port for hanami server

- lib/hanami/cli/generators/gem/app.rb
- lib/hanami/cli/generators/gem/app/404.html
- lib/hanami/cli/generators/gem/app/500.html
- spec/unit/hanami/cli/commands/gem/new_spec.rb
I was tempted to copy Rails' CSS for these, but that felt a bit on the nose, so for now, these are non-styled HTML, and there is now the opportunity for someone to come in and help create nicer looking default error pages in the future :)
> Generate public/ error pages in new app

- lib/hanami/cli/commands/app/generate/action.rb
- lib/hanami/cli/generators/app/action.rb
- lib/hanami/cli/generators/app/action/action.erb
- lib/hanami/cli/generators/app/action/slice_action.erb
- lib/hanami/cli/generators/app/action_context.rb
- spec/unit/hanami/cli/commands/app/generate/action_spec.rb
> Make actions render their view files by default

- lib/hanami/cli/commands/app.rb
- lib/hanami/cli/commands/app/assets/command.rb
- lib/hanami/cli/commands/app/assets/compile.rb
- lib/hanami/cli/commands/app/assets/watch.rb
- lib/hanami/cli/commands/app/generate/action.rb
- lib/hanami/cli/generators/app/action.rb
- lib/hanami/cli/interactive_system_call.rb
- spec/unit/hanami/cli/commands/app/assets/compile_spec.rb
- spec/unit/hanami/cli/commands/app/assets/watch_spec.rb
- spec/unit/hanami/cli/commands/app/generate/action_spec.rb
Ref https://github.com/hanami/assets/pull/124
> Reimplement `hanami-assets` commands: `Hanami::Assets::Precompiler` and `Watcher`

- lib/hanami/cli/bundler.rb
- lib/hanami/cli/command.rb
- lib/hanami/cli/commands/app/command.rb
- lib/hanami/cli/files.rb
Fixes https://github.com/hanami/rspec/issues/16
> Use `Hanami::CLI::Files` consistently

- lib/hanami/cli/generators/gem/app/puma.erb
- spec/unit/hanami/cli/commands/gem/new_spec.rb
Closes https://github.com/hanami/hanami/issues/1340
> `hanami new` to generate documented `config/puma.rb`

- CHANGELOG.md
- lib/hanami/cli/generators/app/slice/app_layout.erb
- lib/hanami/cli/generators/app/slice_context.rb
- lib/hanami/cli/generators/gem/app/app_layout.erb
- spec/unit/hanami/cli/commands/app/generate/slice_spec.rb
- spec/unit/hanami/cli/commands/gem/new_spec.rb
> Use correct helpers in generated layouts

- lib/hanami/cli/generators/gem/app/gemfile.erb
- spec/unit/hanami/cli/commands/gem/new_spec.rb
> Alphabetise the Hanami gems in the generated Gemfile.

- lib/hanami/cli/commands/app/command.rb
- lib/hanami/cli/commands/app/db/migrate.rb
- spec/unit/hanami/cli/commands/app/db/migrate_spec.rb
- spec/unit/hanami/cli/commands/app/db/version_spec.rb
> Dump structure after migrating database

- lib/hanami/cli/commands/app.rb
- lib/hanami/cli/commands/app/db/create.rb
- lib/hanami/cli/commands/app/db/utils/postgres.rb
- spec/unit/hanami/cli/commands/app/db/create_spec.rb
> Enable `db create` command for new db layer

- lib/hanami/cli/commands/app/db/create.rb
- lib/hanami/cli/commands/app/db/drop.rb
- lib/hanami/cli/commands/app/db/utils/postgres.rb
- spec/unit/hanami/cli/commands/app/db/create_spec.rb
- spec/unit/hanami/cli/commands/app/db/drop_spec.rb
> Enable `db drop` command for new db layer

- Gemfile
- hanami-cli.gemspec
This is the release that introduces the `type: :flag` option type.
> Depend on dry-cli v1.1.0

- lib/hanami/cli/generators/context.rb
- lib/hanami/cli/generators/gem/app/gitignore.erb
- spec/unit/hanami/cli/commands/gem/new_spec.rb
Found this when going through the "Building a web app" guide for 2.2
I accidentally committed the DB file 😱
> Add db/*.sqlite to gitignore for sqlite apps

- lib/hanami/cli/generators/app/migration.rb
- spec/unit/hanami/cli/commands/app/generate/migration_spec.rb
This makes it just a little bit easier to write your migration.
Resolves #250
> Generate a change method in new migrations

- lib/hanami/cli/generators/gem/app.rb
- lib/hanami/cli/generators/gem/app/seeds.erb
- spec/unit/hanami/cli/commands/gem/new_spec.rb
> Generate config/db/seeds.rb in new app

- lib/hanami/cli/generators/gem/app/operation.erb
- spec/unit/hanami/cli/commands/gem/new_spec.rb
Closes #1437
This is now being handled by the framework automatically in hanami/hanami#1456
> Remove ROM boilerplate from Operation generator

- lib/hanami/cli/commands/app.rb
> Register generators only if bundled with correct gems

- lib/hanami/cli/commands/app/generate/relation.rb
- lib/hanami/cli/generators/app/relation.rb
- spec/unit/hanami/cli/commands/app/generate/relation_spec.rb
closes [#259](https://github.com/hanami/cli/issues/259)
> add --gateway flag to generate relation

- lib/hanami/cli/commands/gem/new.rb
- lib/hanami/cli/errors.rb
- spec/unit/hanami/cli/commands/gem/new_spec.rb
I'm at RubyConf! Thanks for letting me sit at the hack day table and talk about Hanami a bit. If this is the wrong direction, feel free to pick it apart or summarily close if not exactly what y'all want. Hugs! 🤗 
fixes [#1472](https://github.com/hanami/hanami/issues/1472)
> Don't allow creating a new app with certain confusing names

- lib/hanami/cli/generators/gem/app/readme.erb
- spec/unit/hanami/cli/commands/gem/new_spec.rb
Generated readme additions
Fixes #216
> Generated readme additions

- lib/hanami/cli/generators/app/ruby_file.rb
Still private API while we continue work on this
> Make RubyFile#path public

- lib/hanami/cli/generators/gem/app/dev
- spec/unit/hanami/cli/commands/gem/new_spec.rb
> Disable foreman's `.env` processing
