Gemfile, lib/hanami/cli/commands/monolith/console.rb, lib/hanami/console/context.rb, lib/hanami/console/plugins/slice_readers.rb
This PR makes the slice readers properly available in the console context methods. With the previous approach, they were unavailable (e.g. in the console for our application template, typing `main` would raise a `NoMethodError`).
This could have been fixed most simply by changing `extend(Plugins::SliceReaders.new(app))` inside `Context.extended` so it was actually `other.extend(Plugins::SliceReaders.new(app))`. However, I took this change to refactor this module since we didn't actually have to define all this behavior at the moment of being extended (`other` was never used anywhere!) — since we have all the information we need at the time of initialization, that's the best time to define all the behavior. We can leave the module hooks alone until we actually need access to that `other` …
=> Fix console context (make slice readers properly available)

lib/hanami/cli/repl/irb.rb
This required us not to use IRB.start, which sets all initial vaues of IRB.conf in a place we can't control.
Instead, start IRB manually (by following the steps from the code inside IRB.start) and set our custom prompt config _after_ the initial IRB.conf has been prepared.
This ensures that the prompt will be respected when IRB finally runs.
=> Properly show a custom prompt in IRB

lib/hanami/cli/commands/db/utils/database.rb
According to PostgreSQL's docs, the URL scheme designator can be either
`postgresql://` or `postgres://.
This change duplicates the `"postgres"` entry to support both options.
[Docs](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING):
=> Support `postgresql://` scheme designators

lib/hanami/cli/commands/db/utils/database.rb
The method `init_bootable` is redundant, replaced by `prepare`
Solve issue https://github.com/hanami/cli/issues/10
=> Fix redundant method when loading database command

lib/hanami/cli/commands/db/utils/database.rb
On the latest version of `hanami-template`, running `bin/hanami db version` raises error: `hanami-cli-2.0.0.alpha7/lib/hanami/cli/commands/db/utils/database.rb:114:in `sequel_migrator': uninitialized constant Hanami::CLI::Commands::DB::Utils::Database::Sequel (NameError)`.
This PR loads `Sequel` with `migration` extension before initializing `Sequel::TimestampMigrator`.
=> Import Sequel for db version command

lib/hanami/cli/commands/application.rb, spec/integration/run_spec.rb
Upgrading a Hanami 2 application from the unstable branch to hanami 2.0.0.alpha5, I noticed that — while setting the application environment via the `bin/hanami console --env environment` option works — setting it via a HANAMI_ENV environment variable no longer does:
```bash
bin/hanami console --env production
hanami_app[production]> Hanami.env
=> :production
HANAMI_ENV=production bin/hanami console
hanami_app[development]> Hanami.env
=> :development # expected :production
```
I think this behaviour changed [in this commit](https://github.com/hanami/cli/commit/cd3a7b4458b5d2017fecbbe47d992fc068d5ebfb), in part due to the adoption of the development default? 
This PR proposes adjusting how Hanami.env is determined to adhere to the following:
- first use any environment specified via the …
=> Respect HANAMI_ENV if command line env option is not specified.

hanami-cli.gemspec, lib/hanami/cli/commands/application/server.rb, lib/hanami/cli/server.rb, spec/fixtures/test/config.ru, spec/unit/hanami/cli/commands/application/server_spec.rb, spec/unit/hanami/cli/server_spec.rb
The server is just a thin wrapper on top of Rack::Server. The options
that it accepts fall into two different categories:
- When not explicitly set, port and host are not passed to the rack
server instance. This way, they can be configured through the configured
rack handler (e.g., the puma configuration file).
- All others are always given by the Hanami command.
The test for the command forks a new process so that the one running the
tests is not blocked and can assert that endpoint is working. Standard
outputs are silenced to avoid the command output being rendered.
Replaces #12
See https://github.com/puma/puma/pull/2832 for issue on Puma
=> Add `hanami server` command

Gemfile, lib/hanami/cli/commands/app.rb, lib/hanami/cli/commands/app/routes.rb, spec/fixtures/test/config/routes.rb, spec/unit/hanami/cli/commands/app/routes_spec.rb
Without the `slice` option, it will inspect the application routes:
```ruby
$ hanami routes
```
All the formatters available from `hanami-router` are available:
```ruby
$ hanami routes --format=csv
```
A custom formatter registered in the application container can also be
used. It needs to be identified by its key:
```ruby
$ hanami routes --format=custom_routes_formatter
```
=> Add `hanami routes` command

lib/hanami/cli/generators/gem/app/gemfile.erb, spec/unit/hanami/cli/commands/gem/new_spec.rb
Resolves: https://trello.com/c/Lx86f21b/192-hanami-validations-not-included-in-a-brand-new-application
When you create a new hanami app, using `hanami new`, the `hanami-validations` is not included. This results in a problem, where we cannot use
```ruby
params do
end
```
within actions - I believe this should be built-in feature.
=> Restore hanami-validations

Gemfile, lib/hanami/cli/commands/app.rb, lib/hanami/cli/commands/app/command.rb, lib/hanami/cli/commands/app/console.rb, lib/hanami/cli/commands/app/generate.rb, lib/hanami/cli/generators/app/slice.rb, lib/hanami/cli/generators/app/slice/routes.erb, lib/hanami/cli/generators/app/slice/slice.erb, spec/integration/run_spec.rb, spec/unit/hanami/cli/commands/app/generate/slice_spec.rb
Add `hanami generate slice` CLI command to Hanami applications.
It performs the following actions:
* Edit `config/routes.rb` to add a `slice` block
* Create `slices/[slice]` directory
* Create `slices/[slice]/action.rb` file (with `MySlice::Action < MyApp::Action` class definition)
* Create `slices/[slice]/actions/.keep` file
Example:
```shell
⚡ bundle exec hanami generate slice admin
⚡ tree slices
slices
└── admin
├── action.rb
└── actions
2 directories, 1 file
```
=> Introduce `hanami generate slice`

Gemfile, lib/hanami/cli/commands.rb, spec/unit/hanami/cli/commands/app/generate/action_spec.rb, spec/unit/hanami/cli/commands/app/generate/slice_spec.rb
Use the robust app file detection introduced in hanami/hanami#1197, to allow the CLI to be run even within nested directories and still find the Hanami app file at `config/app.rb` in the project root.
=> Leverage Hanami's file detection

.rubocop.yml, lib/hanami/cli/commands/app.rb, lib/hanami/cli/commands/app/middlewares.rb, lib/hanami/cli/middleware_stack_inspector.rb, spec/unit/hanami/cli/commands/app/middlewares_spec.rb, spec/unit/hanami/cli/middleware_stack_inspector_spec.rb
This command lists all registered middlewares in the app router along
with the paths where they apply:
```
$ hanami middlewares
/    Rack::Session::Cookie
```
Given arguments can be inspected:
```
$ hanami middlewares --with-arguments
/    Rack::Session::Cookie args: [{:secret=>"foo"}
```
=> Add `hanami middlewares` command

.rubocop.yml, Gemfile, lib/hanami/cli/commands/app.rb, lib/hanami/cli/commands/app/generate.rb, lib/hanami/cli/commands/app/generate/action.rb, lib/hanami/cli/generators/app/action.rb, lib/hanami/cli/generators/app/action/action.erb, lib/hanami/cli/generators/app/action/slice_action.erb, lib/hanami/cli/generators/app/action_context.rb, lib/hanami/cli/generators/app/slice/action.erb, spec/unit/hanami/cli/commands/app/generate/action_spec.rb, spec/unit/hanami/cli/commands/app/generate/slice_spec.rb
Add `hanami generate action` CLI command to Hanami applications.
It performs the following actions:
* Edit `config/routes.rb` to add a the route
* Create `app/actions/[controller]` directory
* Create `app/actions/[controller]/[action].rb` file (with `MyApp::Actions::Books::Index < MyApp::Action` class definition)
Example:
```shell
⚡ bundle exec hanami generate action books.index
```
```shell
⚡ tree app
app
├── action.rb
└── actions
└── books
└── index.rb
2 directories, 2 files
```
`config/routes.rb`
```ruby
require "hanami/routes"
module Bookshelf
class Routes < Hanami::Routes
define do
root { "Hello from Hanami" }
get "/books", to: "books.index"
end
end
end
``` 
`app/actions/books/index.rb`
```ruby
module Bookshelf
module Actions
module Books
class Index < Bookshelf::Action
def …
```
=> Introduce `hanami generate action`

lib/hanami/cli/generators/app/action/action.erb, lib/hanami/cli/generators/app/action/slice_action.erb, lib/hanami/cli/generators/app/action/template.html.erb, lib/hanami/cli/generators/app/action/view.erb, lib/hanami/cli/generators/app/action_context.rb, lib/hanami/cli/generators/app/slice/action.erb, lib/hanami/cli/generators/app/slice/entities.erb, lib/hanami/cli/generators/app/slice/repository.erb, lib/hanami/cli/generators/app/slice/slice.erb, lib/hanami/cli/generators/app/slice/view.erb, lib/hanami/cli/generators/app/slice_context.rb, lib/hanami/cli/generators/context.rb, lib/hanami/cli/generators/gem/app/action.erb, lib/hanami/cli/generators/gem/app/app.erb, lib/hanami/cli/generators/gem/app/readme.erb, lib/hanami/cli/generators/gem/app/routes.erb, lib/hanami/cli/generators/gem/app/settings.erb, lib/hanami/cli/generators/gem/app/types.erb, lib/hanami/cli/generators/gem/app/validator.erb, spec/unit/hanami/cli/commands/app/generate/action_spec.rb, spec/unit/hanami/cli/commands/gem/new_spec.rb
```shell
⚡hanami new rubygems
```
```ruby
Hanami.app # => Rubygem::Application
```
```ruby
Hanami.app # => Rubygems::Application
```
---
Closes #37 
https://trello.com/c/UoexUHqg
=> Respect plural name when generate code

lib/hanami/cli/generators/gem/app.rb, lib/hanami/cli/generators/gem/app/puma.erb, spec/unit/hanami/cli/commands/gem/new_spec.rb
`config/puma.rb`
```ruby
max_threads_count = ENV.fetch("HANAMI_MAX_THREADS", 5)
min_threads_count = ENV.fetch("HANAMI_MIN_THREADS") { max_threads_count }
threads min_threads_count, max_threads_count
port        ENV.fetch("HANAMI_PORT", 2300)
environment ENV.fetch("HANAMI_ENV", "development")
workers     ENV.fetch("HANAMI_WEB_CONCURRENCY", 2)
on_worker_boot do
Hanami.shutdown
end
preload_app!
```
---
https://trello.com/c/V3IMSlso
=> `hanami new` to generate Puma configuration

lib/hanami/cli/generators/app/action.rb, spec/unit/hanami/cli/commands/app/generate/action_spec.rb
Example:
```shell
⚡bundle exec hanami generate action talent.apply
```
Before this fix, it was crashing.
---
Ref https://trello.com/c/FYeNF65B
=> Ensure `hanami generate action` to work with non-RESTful actions

lib/hanami/cli/generators/gem/app/gemfile.erb, spec/unit/hanami/cli/commands/gem/new_spec.rb
Use `hanami-reloader` by default.
=> `hanami new` to add `hanami-reloader` to `Gemfile`

spec/fixtures/test/config/routes.rb
No longer needs (or can use) the  block
https://github.com/hanami/hanami/pull/1208
Note that this is different from #45, which is about the apps that this cli generates, whereas this is to make the test suite for this repo green again.
=> Fix routes definition in test app

lib/hanami/cli/commands/gem/new.rb, spec/unit/hanami/cli/commands/gem/new_spec.rb, spec/unit/hanami/cli/middleware_stack_inspector_spec.rb
Advertise Bundler & Hanami installation while running `hanami new`
```shell
⚡ hanami new bookshelf
-> Within bookshelf/
⚡ hanami new bookshelf
Created bookshelf/
-> Within bookshelf/
Created .env
Created README.md
Created Gemfile
Created Rakefile
Created config.ru
Created config/app.rb
Created config/settings.rb
Created config/routes.rb
Created config/puma.rb
Created lib/tasks/.keep
Created lib/bookshelf/types.rb
Created app/actions/.keep
Created app/action.rb
Running Bundler install...
Running Hanami install...
```
👉 The last two lines are the addition of this enhancement.
Bundler, and potentially Hanami, installation can be time consuming.
Without advertising their execution, the user has the impression that `hanami new` is stuck at the last file creation (e.g. `Created app/action.rb`).
=> Advertise Bundler & Hanami installation while running `hanami new`

lib/hanami/cli/command.rb, lib/hanami/cli/commands/app.rb, lib/hanami/cli/commands/app/console.rb, lib/hanami/cli/commands/app/generate/action.rb, lib/hanami/cli/commands/app/generate/slice.rb, lib/hanami/cli/commands/app/install.rb, lib/hanami/cli/commands/app/middleware.rb, lib/hanami/cli/commands/app/middlewares.rb, lib/hanami/cli/commands/app/routes.rb, lib/hanami/cli/commands/app/server.rb, lib/hanami/cli/commands/app/version.rb, lib/hanami/cli/commands/gem/new.rb, lib/hanami/cli/commands/gem/version.rb, lib/hanami/cli/generators/app/slice.rb, lib/hanami/cli/generators/app/slice/routes.erb, lib/hanami/cli/generators/app/slice_context.rb, lib/hanami/cli/middleware_stack_inspector.rb, spec/integration/run_spec.rb, spec/unit/hanami/cli/commands/app/generate/slice_spec.rb, spec/unit/hanami/cli/commands/app/middleware_spec.rb
Tidy `--help` of all the `hanami` commands.
---
* `hanami middlewares` -> `hanami middleware`
* `hanami generate slice --url-prefix` -> `--url` for parity with `hanami generate action`, which accepts a `--url` option
* `hanami new --skip-bundle` --> `--skip-install` to communicate that both Bundler and Hanami installation are skipped 
---
* `Hanami::CLI::Command#initialize` superclass injects `err:` as dependency. It defaults to `$stderr`.
* `Hanami::CLI::Command::App::Console` renamed REPL to Engine to low level adapter like IRB, Pry, etc..
---
Outside an application
```shell
⚡ hanami --help
Commands:
hanami new APP         # Generate a new Hanami app
hanami version         # Hanami version
```
```shell
⚡ hanami new --help
Command:
hanami new
Usage:
hanami new APP
Description:
Generate a …
```
=> Tidy `hanami` help

lib/hanami/cli/generators/gem/app/settings.erb, spec/unit/hanami/cli/commands/gem/new_spec.rb
Given the settings class can be accessed extremely early during app boot (i.e. inside the app class body), we're avoiding any dependencies on other files within the app, and instead auto-generating a Types module nested inside the Settings class for easy access to type checking.
=> Remove types require from config/settings.rb

.rubocop.yml, lib/hanami/cli/commands.rb
This allows the hanami CLI to expose its app commands even if invoked from a deeper app directory.
Since this may have caused an issue with the CLI properly executing in earlier testing (before our 2.0.0.beta3 release), wrap the call to `Hanami.app_path` in a rescue that will fall back to a simpler mechanism that will still work in the common cases.
=> Use Hanami.app_path to find if we're in an app

lib/hanami/cli/commands/gem/new.rb, lib/hanami/cli/errors.rb, spec/unit/hanami/cli/commands/gem/new_spec.rb
Closes #52 (and reported in #59 by someone who is not me)
```bash
% mkdir bookshelf # or `touch bookshelf`
% exe/hanami new bookshelf
Cannot create new Hanami app in an existing folder bookshelf/
```
This is simpler than prompting the user to decide if we should still proceed. They can decide or move folders around.
=> Raise exception if trying to create Hanami app in existing folder (or file)

lib/hanami/cli/commands/app/command.rb
I know this isn't a supported Hanami 2.0.0 issue, but it does help with keeping the database CLI commands working :)
=> Add missing App namespace for database reference.

lib/hanami/cli/commands/app/generate/action.rb, lib/hanami/cli/naming.rb, spec/unit/hanami/cli/commands/app/generate/action_spec.rb
Closes https://github.com/hanami/cli/issues/69
---
This is the bare minimum code to fix the issue.
I'm already working locally to refactor to expand the usage of `Hanami::CLI::Naming` in the entire codebase.
=> Fix: allow to generate deeply nested action with correct container key

lib/hanami/cli/commands/app/db/rollback.rb, lib/hanami/cli/commands/app/db/utils/database.rb, spec/unit/hanami/cli/commands/app/db/rollback_spec.rb
Fix rollback command as its currently not working correctly.
* The current implementation of rollback is passing the incorrect target to the `database` class. It's passing the target version of the latest migration instead of the previous one. This is resulting in no rollback occurring. 
* Another issue is that the block being passed to `measure` does not return true if successful, resulting in a failure message displaying all the time, even on successful rollbacks.
* Make the rollback command a bit smarter by allowing it to figure out correctly what the applied migrations are and what the intention is based on if a target is provided or not.
* Pass the `latest_migration - 1` in to ensure the rollback target is one prior to the latest applied migration
* Wrap ` …
=> Fix rollback command

lib/hanami/cli/generators/gem/app/puma.erb, spec/unit/hanami/cli/commands/gem/new_spec.rb
We want to ensure that Hanami runs using the lowest memory footprint by
default.
=> Start puma in `single-mode` by default.

lib/hanami/cli/commands/app.rb, lib/hanami/cli/commands/app/generate/action.rb, lib/hanami/cli/commands/app/generate/view.rb, lib/hanami/cli/generators/app/action.rb, lib/hanami/cli/generators/app/action/slice_template.html.erb, lib/hanami/cli/generators/app/action/slice_view.erb, lib/hanami/cli/generators/app/action/template.html.erb, lib/hanami/cli/generators/app/slice.rb, lib/hanami/cli/generators/app/slice/view.erb, lib/hanami/cli/generators/app/view.rb, lib/hanami/cli/generators/app/view/app_template.html.erb, lib/hanami/cli/generators/app/view/app_view.erb, lib/hanami/cli/generators/app/view/slice_template.html.erb, lib/hanami/cli/generators/app/view/slice_view.erb, lib/hanami/cli/generators/app/view_context.rb, lib/hanami/cli/generators/gem/app.rb, lib/hanami/cli/generators/gem/app/view.erb, spec/unit/hanami/cli/commands/app/generate/action_spec.rb, spec/unit/hanami/cli/commands/app/generate/view_spec.rb, spec/unit/hanami/cli/commands/gem/new_spec.rb
Add support for generating views:
- When generating a new app, via `hanami new`
- When generating an action, via `hanami generate action`
- Independently, via `hanami generate view`
=> View generators

lib/hanami/cli/commands/app.rb, lib/hanami/cli/commands/app/assets.rb, lib/hanami/cli/commands/app/assets/compile.rb, lib/hanami/cli/commands/app/assets/watch.rb, lib/hanami/cli/interactive_system_call.rb, spec/unit/hanami/cli/commands/app/assets/compile_spec.rb, spec/unit/hanami/cli/commands/app/assets/watch_spec.rb
Introduce two new commands:
* `hanami assets compile` to compile the assets during deployments
* `hanami assets watch` to watch and lazily compile assets during development
---
Ref https://github.com/hanami/assets/pull/120
=> Introduce `hanami assets` commands

lib/hanami/cli/commands/app.rb, lib/hanami/cli/commands/app/dev.rb, spec/unit/hanami/cli/commands/app/dev_spec.rb
Introduce a new command for development: `hanami dev`.
It's a convenient wrapper around Foreman.
Our goal is to provide an easy-to-remember command to start a development session.
By default, it will look at `Procfile.dev`.
You can customize the path to find the file with:
```bash
$ bundle exec hanami dev -f /path/to/your/Procfile
```
=> Introduce `hanami dev`

Gemfile, lib/hanami/cli/commands/app/assets/compile.rb, lib/hanami/cli/commands/app/assets/watch.rb, spec/fixtures/test/config/app.rb, spec/unit/hanami/cli/commands/app/assets/compile_spec.rb, spec/unit/hanami/cli/commands/app/assets/watch_spec.rb
For the `assets compile` and `assets watch` commands, instead of hardcoding a default path to the `hanami-assets.js` command, use the configured exe path at `Hanami.app.assets.exe_path`.
Resolves #96.
=> Use app's configured assets exe_path for commands

CHANGELOG.md, lib/hanami/cli/generators/gem/app/gemfile.erb, spec/unit/hanami/cli/commands/gem/new_spec.rb
This is the [recommended](https://github.com/BetterErrors/better_errors#installation) way to use `better_errors`, the engine that powers `hanami-webconsole`.
=> `hanami new` generates a `Gemfile` with `hanami-webconsole` in `:development` group

CHANGELOG.md, lib/hanami/cli/commands/gem/new.rb, lib/hanami/cli/generators/context.rb, lib/hanami/cli/generators/gem/app/gemfile.erb, spec/unit/hanami/cli/commands/gem/new_spec.rb
Example:
```
$ hanami new bookshelf --head
```
This command will generate a new app using the Hanami HEAD version from GitHub's `main` branches.
The `Gemfile` will look like this:
```ruby
gem "hanami", github: "hanami/hanami", branch: "main"
gem "hanami-router", github: "hanami/router", branch: "main"
```
`hanami new` to generate a `Gemifile` with versioned Hanami development gems like `hanami-webconsole`, `hanami-reloader`, `hanami-rspec`.
`Gemfile` Example
```ruby
gem "hanami-webconsole", "~> 2.1"
```
=> Generate Hanami app using HEAD version from GitHub

Gemfile, lib/hanami/cli/commands/app/assets/command.rb, lib/hanami/cli/commands/app/assets/watch.rb, lib/hanami/cli/commands/app/install.rb, lib/hanami/cli/commands/gem/new.rb, lib/hanami/cli/generators/context.rb, lib/hanami/cli/generators/gem/app.rb, lib/hanami/cli/generators/gem/app/assets.mjs, lib/hanami/cli/generators/gem/app/package.json.erb, lib/hanami/cli/generators/version.rb, spec/unit/hanami/cli/commands/app/assets/compile_spec.rb, spec/unit/hanami/cli/commands/app/assets/watch_spec.rb, spec/unit/hanami/cli/commands/app/install_spec.rb, spec/unit/hanami/cli/commands/gem/new_spec.rb
Prepare for our updated approach to assets chiefly introduced with https://github.com/hanami/assets-js/pull/10.
Update `hanami new`:
- Generate a new `config/assets.mjs` that will be needed for our new way of running the assets commands (see https://github.com/hanami/assets-js/pull/10)
- - Generate a leaner `package.json`, including an `"assets"` entry in the `"scripts"` section, referencing the above `config/assets.mjs` file.
Update the `hanami assets compile` and `hanami assets watch` commands:
- Expect to run assets via `npm run assets`, as generated in the new `package.json` above.
- Have these use a single hanami-assets setting for running these commands: `package_manager_run_command` (introduced in https://github.com/hanami/assets/pull/131), which defaults to `npm run`.
=> Generate and install new assets arrangement

spec/unit/hanami/cli/commands/app/middleware_spec.rb
This is a new default middleware, as of https://github.com/hanami/hanami/pull/1344.
Update the tests to include this middleware to keep the build green here.
=> Include MethodOverride middleware in test output

lib/hanami/cli/generators/gem/app/routes.erb, spec/unit/hanami/cli/commands/gem/new_spec.rb
Provide an explanatory comment inside the routes class instead.
This root route is no longer needed now that we’ll be providing a welcome view when no routes are defined (see https://github.com/hanami/hanami/pull/1353).
=> Stop generating a default root route

Gemfile, lib/hanami/cli/commands/app/dev.rb, lib/hanami/cli/generators/gem/app.rb, lib/hanami/cli/generators/gem/app/dev, spec/unit/hanami/cli/commands/app/dev_spec.rb, spec/unit/hanami/cli/commands/gem/new_spec.rb
When generating a new app, create an executable `bin/dev` file with the following contents:
```sh
#!/usr/bin/env sh
if ! gem list foreman -i --silent; then
echo "Installing foreman..."
gem install foreman
fi
exec foreman start -f Procfile.dev "$@"
```
This ensures that the `foreman` gem is installed as part of the first start of Hanami without requiring any explicit user action.
From here, update `hanami dev` to become a simple wrapper for calling `bin/dev`.
This is in keeping with our recently adjusted approach for `hanami assets`, with its `compile` and `watch` subcommands are just simple wrappers for calling `npm run assets`.
From this arrangement, we get a few benefits:
1. As above, the user no longer has to explicitly install foreman, which streamlines the Hanami first run …
=> Generate bin/dev that installs foreman, and call from it from `hanami dev`

lib/hanami/cli/generators/gem/app/404.html, lib/hanami/cli/generators/gem/app/500.html
Add the lovely new error page designs from @aaronmoodie. Thank you again Aaron for bringing this touch of class to new Hanami apps!
This includes both 404 and 500 error pages. Here’s the 404 page as an example for you to feast your eyes upon:
Light, elegant, and informative. A great default that new Hanami apps could very happily live with until they're ready to provide their own designs!
Resolves #115
=> Add new error page designs

lib/hanami/cli/commands/app.rb, lib/hanami/cli/commands/app/generate/part.rb, lib/hanami/cli/generators/app/part.rb, lib/hanami/cli/generators/app/part/app_base_part.erb, lib/hanami/cli/generators/app/part/app_part.erb, lib/hanami/cli/generators/app/part/slice_base_part.erb, lib/hanami/cli/generators/app/part/slice_part.erb, lib/hanami/cli/generators/app/part_context.rb, spec/unit/hanami/cli/commands/app/generate/part_spec.rb
Introduce a new CLI command to generate View Parts.
If the base part of the app (or slice) is missing, generate it.
```shell
$ bundle exec hanami generate part author
Created app/views/part.rb
Created app/views/parts/
Created app/views/parts/author.rb
```
`app/views/part.rb`
```ruby
module Bookshelf
module Views
class Part < Hanami::View::Part
end
end
end
```
`app/views/parts/author.rb`
```ruby
module Bookshelf
module Views
module Parts
class Author < Bookshelf::Views::Part
end
end
end
end
```
```shell
$ bundle exec hanami generate part book
Created app/views/parts/book.rb
```
```shell
$ bundle exec hanami generate part user --slice=admin
Created app/views/part.rb
Created slices/admin/views/part.rb
Created slices/admin/views/parts/
Created slices/admin/views/parts/user.rb
``` …
=> Introduce `hanami generate part` CLI command

lib/hanami/cli/generators/app/action.rb, spec/unit/hanami/cli/commands/app/generate/action_spec.rb
When generating Create and Update actions, skip the view generation if the corresponding RESTful actions are there.
| Action | Corresponding RESTFul Action |
|--------|--------|
| Create | New |
| Update | Edit | 
This behavior is replicated for slices as well.
Skips the view creation:
```shell
⚡ bundle exec hanami generate action books.create
Updated config/routes.rb
Created app/actions/books/create.rb
Created spec/actions/books/create_spec.rb
```
It generates the view:
```shell
⚡ bundle exec hanami generate action authors.create
Updated config/routes.rb
Created app/actions/authors/
Created app/actions/authors/create.rb
Created app/views/authors/
Created app/views/authors/create.rb
Created app/templates/authors/
Created app/templates/authors/create.html.erb
Created …
```
=> Skip view RESTful view generation

lib/hanami/cli/generators/context.rb, spec/unit/hanami/cli/generators/context_spec.rb
Ref https://github.com/hanami/rspec/pull/18
Ref #113 
Ref #117
=> Introducing private API method: `Hanami::CLI::Generators::Context#ruby_implicity_keyword_argument?`

lib/hanami/cli/commands/app/assets/command.rb, lib/hanami/cli/commands/app/assets/compile.rb
We're not using the `entry_points` and `destination` assets settings right now. These are currently hardcoded inside assets-js, so remove these references to avoid any confusion that we may be able to configure these from the outside. See https://github.com/hanami/assets/pull/132, where we're removing those settings directly from the hanami-assets gem.
While we're here, properly shellescape the `sri` argument given to the assets CLI.
=> Remove unused assets settings

lib/hanami/cli/commands/app/generate/action.rb, lib/hanami/cli/commands/app/generate/part.rb
This will allow hanami-rspec to observe this flag and skip its work if true.
This is in service of making sure we don't generate spurious (and failing) tests in our new 2.1 getting started guide for web apps.
(More generally, it would be nice if gems adding hooks around the core CLI commands could register their own options, since that would mean we could limit these changes to the hanami-rspec gem only, but for now, we have to make this change to register the flag here, and then use the flag over there)
=> Add --skip-tests flag to generate commands

lib/hanami/cli/commands/gem/new.rb
Sample output now:
```sh
% exe/hanami new bookshelf
Created bookshelf/
-> Within bookshelf/
Created .gitignore
Created .env
Created README.md
Created Gemfile
Created Rakefile
Created Procfile.dev
Created config.ru
Created bin/dev
Created config/app.rb
Created config/settings.rb
Created config/routes.rb
Created config/puma.rb
Created lib/tasks/.keep
Created lib/bookshelf/types.rb
Created app/actions/.keep
Created app/action.rb
Created app/view.rb
Created app/views/helpers.rb
Created app/templates/layouts/app.html.erb
Created package.json
Created config/assets.mjs
Created app/assets/js/app.js
Created app/assets/css/app.css
Created app/assets/images/favicon.ico
Created public/404.html
Created public/500.html
Running Bundler install...
Running npm install...
NPM ERROR:
npm ERR! code ETARGET …
```
=> Show errors when NPM install fails

lib/hanami/cli/commands/gem/new.rb, spec/unit/hanami/cli/commands/gem/new_spec.rb
To ensure any new Gemfile entries are installed
=> Run bundle check || bundle install after hanami install

.rubocop.yml, Gemfile, lib/hanami/cli/commands/app/assets/command.rb, lib/hanami/cli/commands/app/assets/compile.rb, lib/hanami/cli/commands/app/assets/watch.rb, lib/hanami/cli/interactive_system_call.rb, spec/integration/run_spec.rb, spec/spec_helper.rb, spec/support/app_integration.rb, spec/unit/hanami/cli/commands/app/assets/compile_spec.rb, spec/unit/hanami/cli/commands/app/assets/watch_spec.rb, spec/unit/hanami/cli/commands/app/generate/slice_spec.rb
Build upon https://github.com/hanami/assets-js/pull/20 and update the `assets compile` and `assets watch` commands to fork a child process per slice and run a separate assets command per each.
Provide appropriate `--path` and `--dest` flags for each of these commands, allowing each slice's assets to be compiled separately and generated into distinct directories (`public/assets/` for the app, and `public/assets/[slice_name]/` for slices).
Supports per-slice assets config, by running a slice's own `config/assets.js`, if present, otherwise falling back to the app's `config/assets.js`.
Finally, incorporates hanami/assets#138, using the new `node_command` setting to invoke node when running the `config/assets.js` command.
=> Run multiple assets processes

lib/hanami/cli/commands/app/assets/command.rb, spec/unit/hanami/cli/commands/app/assets/compile_spec.rb, spec/unit/hanami/cli/commands/app/assets/watch_spec.rb
For the app, assets live inside /app/assets, instead of just /assets.
=> Properly detect assets inside app/assets/

lib/hanami/cli/command.rb, lib/hanami/cli/commands/app/assets/command.rb, lib/hanami/cli/commands/app/assets/compile.rb, lib/hanami/cli/commands/app/assets/watch.rb, lib/hanami/cli/commands/app/dev.rb, lib/hanami/cli/commands/app/generate/action.rb, lib/hanami/cli/commands/app/generate/part.rb, lib/hanami/cli/commands/app/generate/slice.rb, lib/hanami/cli/commands/app/generate/view.rb, lib/hanami/cli/commands/app/server.rb, lib/hanami/cli/commands/gem/new.rb, spec/unit/hanami/cli/commands/app/dev_spec.rb
This allows these default args to be already provided by the time any subclass `#initialize`  is called, which means they can be accessed inside that method (or even inside its other default args) without the same defaults having to be re-provided.
For example, a subclass that needs `out:` and `err:` can now do this:
```ruby
def initialize(out:, err:, inflector:, another: AnotherClass.new(out:, err:, inflector:), **opts)
super(out:, err:, inflector:, **opts)
@another = another
end
```
Where previously, redefining the default args was necessary:
```ruby
def initialize(out: $stdout, err:, $stderr, inflector: Dry::Inflector.new, another: AnotherClass.new(out:, err:, inflector:), **opts)
super(out:, err:, inflector:, **opts)
@another = another
end
```
This arrangement required unnecessary …
=> Provide command default args via `.new` instead of `#initialize`

lib/hanami/cli/generators/gem/app/package.json.erb, spec/unit/hanami/cli/commands/gem/new_spec.rb
We no longer need this. Instead, our assets CLI commands are detecting the `config/assets.js` file and calling it directly.
Fixes #133.
=> Remove "assets" from package.json "scripts" section

lib/hanami/cli/generators/app/slice_context.rb, spec/unit/hanami/cli/commands/app/generate/slice_spec.rb
This is no longer necessary with the independent assets per slice.
=> Don’t namespace asset tags for slice layouts

lib/hanami/cli/commands/app/assets/command.rb, spec/unit/hanami/cli/commands/app/assets/compile_spec.rb, spec/unit/hanami/cli/commands/app/assets/watch_spec.rb
This will avoid naming collisions with ordinary user-controlled files or directories.
Uses the new `Hanami::Assets.public_assets_dir` method introduced in https://github.com/hanami/assets/pull/140.
=> Underscore slice names in public asset dirs

lib/hanami/cli/commands/app/assets/command.rb
When I use `hanami assets watch` and then close it with Ctrl+C, I see:
```
hanami assets watch
[blog] [watch] build finished, watching for changes...
^C/Users/ryan.bigg/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/hanami-cli-2.1.0/lib/hanami/cli/commands/app/assets/command.rb:65:in `block (2 levels) in call': undefined local variable or method `sig' for #<Hanami::CLI::Commands::App::Assets::Watch:0x00000001103fdc00 @app=Blog::App, @out=#<IO:<STDOUT>>, @err=#<IO:<STDERR>>, @fs=#<Hanami::CLI::Files:0x00000001104fc340 @adapter=#<Dry::Files::FileSystem:0x00000001104fc1d8 @file=File, @file_utils=FileUtils>, @out=#<IO:<STDOUT>>>, @inflector=#<Dry::Inflector>, @config=#<Hanami::Config::Assets:0x0000000107cf10e0 @__config__=#<Dry::Configurable::Config values={:serve=>true}>, …
```
=> Use stringified signal when Ctrl+C received by assets command

Gemfile, lib/hanami/cli/commands/app.rb, lib/hanami/cli/commands/app/db/command.rb, lib/hanami/cli/commands/app/db/migrate.rb, lib/hanami/cli/commands/app/db/utils/database.rb, lib/hanami/cli/commands/app/db/utils/postgres.rb, lib/hanami/cli/commands/app/db/utils/sqlite.rb, spec/unit/hanami/cli/commands/app/db/migrate_spec.rb
Update `db migrate` to work for multiple databases configured across the app and its slices.
To find databases to operate on, it:
1. Looks for all slices (app included) with a `:db` provider present, and groups these by their database URLs
2. For each database URL, finds the slice that has a `config/db/` directory - this is considered the "canonical" slice for the database. 
3. Migrates the database for each such slice.
- If >1 slices have a config/db/, it prints a warning, and choose to operate on the first slice only.
The command also supports the following arguments:
- `--app` to operate on the app's db only
- `--slice=slice_name` to operate on a specific slice's database (in this case, we operate directly on that slice, and don't take the steps noted above to try and find the …
=> Update `db migrate` for new db layer

lib/hanami/cli/commands/app.rb, lib/hanami/cli/commands/app/db/command.rb, lib/hanami/cli/commands/app/db/migrate.rb, lib/hanami/cli/commands/app/db/utils/database.rb, lib/hanami/cli/commands/app/db/version.rb, spec/unit/hanami/cli/commands/app/db/version_spec.rb
Update `db version` to work for multiple databases configured across the app and its slices.
To find databases to operate on, it uses the same approach devised in #160:
1. Looks for all slices (app included) with a `:db` provider present, and groups these by their database URLs
2. For each database URL, finds the slice that has a `config/db/` directory - this is considered the "canonical" slice for the database. 
The command also supports the following arguments:
- `--app` to use the app's db only
- `--slice=slice_name` to use the db for a specific slice (in this case, we operate directly on that slice, and don't take the steps noted above to try and find the canonical slice for the database; we trust that the user has provided the right slice via this argument)
Resolves #156
=> Update `db version` for new db layer

lib/hanami/cli/commands/app.rb, lib/hanami/cli/commands/app/generate/component.rb, lib/hanami/cli/generators/app/component.rb, lib/hanami/cli/generators/app/component/component.erb, lib/hanami/cli/generators/app/component/slice_component.erb, lib/hanami/cli/generators/app/component_context.rb, spec/unit/hanami/cli/commands/app/generate/component_spec.rb
Hi. I noticed this task in Hanami github projects: https://github.com/orgs/hanami/projects/2?pane=issue&itemId=37953496
Thought I give it a go, to get acquainted with dry-rb and hanami source code more, and maybe be useful to maintainers as a side effect. I know the task was marked as "maybe" but I often wrote generators for rails and wanted to see how much different would it be here.
The generator is really simple, as components are general objects with no one interface or anything. It is basically a shortcut to creating a file with the right name in the right scope and slice or no slice. That is what I understood that the idea was behind this task.
I also accounted for CLI receiving the name in Pascal Case like `Opeations::CreateUser`. This is a personal preference, since this is how I …
=> Implement generic component generator

lib/hanami/cli/commands/app/generate/component.rb
This adapts to https://github.com/hanami/cli/pull/137/files which was created after I created https://github.com/hanami/cli/pull/130 but merged before it. My branch wasn't rebased before merge and since it was new files, there was no conflict. 
This change simply adapts to what the parent object does now withi default initialize params.
=> Adapt component generator to new command defaults

lib/hanami/cli/commands/app/db/command.rb, lib/hanami/cli/commands/app/db/utils/database.rb
Now that dry-system is updated to find and load providers when accessing them via `#[]` (see https://github.com/dry-rb/dry-system/pull/273), we can use this shorter, nicer method.
=> Load providers via `#[]`

Gemfile, lib/hanami/cli/commands/app.rb, lib/hanami/cli/commands/app/db/command.rb, lib/hanami/cli/commands/app/db/structure/dump.rb, lib/hanami/cli/commands/app/db/utils/database.rb, lib/hanami/cli/commands/app/db/utils/postgres.rb, lib/hanami/cli/commands/app/db/utils/sqlite.rb, spec/unit/hanami/cli/commands/app/db/structure/dump_spec.rb
Enable the `db structure dump` command for our new database layer, and add tests covering its use with Postgres. Support for other database types will follow later (see #157, #158).
As part of this change, make `Hanami::Providers::DB#database_url` public API, and access it through `slice.container.providers[:db].source.database_url` (with `Dry::System::Provider#source` soon to be tagged as public API too).
This ensures that the canonical databases across an app can be identified via their database URL strings alone, without having to establish a full connection to the database. This means all the `db` CLI commands (not just `structure dump`) can operate more efficiently. It also makes them easier to test inside the repo, since we can avoid providing the live database servers for them to …
=> Enable `db structure dump` for new db layer

lib/hanami/cli/commands/app.rb, lib/hanami/cli/commands/app/db/structure/load.rb, lib/hanami/cli/commands/app/db/utils/database.rb, lib/hanami/cli/commands/app/db/utils/mysql.rb, lib/hanami/cli/commands/app/db/utils/postgres.rb, lib/hanami/cli/commands/app/db/utils/sqlite.rb, spec/unit/hanami/cli/commands/app/db/structure/dump_spec.rb, spec/unit/hanami/cli/commands/app/db/structure/load_spec.rb
Add a `db structure load` command for our new database layer, and add tests covering its use with Postgres. Support for other database types will follow later (see #157, #158).
This includes better handling of errors compared to its counterpart `db structure dump` command. I'll return to improve that command in the next PR.
Resolves #155.
=> Add `db structure load` for new db layer

lib/hanami/cli/commands/app/db/structure/dump.rb, lib/hanami/cli/commands/app/db/utils/database.rb, lib/hanami/cli/commands/app/db/utils/mysql.rb, lib/hanami/cli/commands/app/db/utils/postgres.rb, lib/hanami/cli/commands/app/db/utils/sqlite.rb, spec/unit/hanami/cli/commands/app/db/structure/dump_spec.rb
Show structure file paths relative from the app root. Show the error output from the `pg_dump` command if it fails.
=> Improve `db structure dump` output and error handling

.github/workflows/ci.yml, Gemfile, docker-compose.yml, lib/hanami/cli/commands/app/db/structure/dump.rb, lib/hanami/cli/commands/app/db/utils/database.rb, lib/hanami/cli/commands/app/db/utils/postgres.rb, spec/support/postgres.rb, spec/unit/hanami/cli/commands/app/db/structure/dump_spec.rb
This will make it possible to cleanly run migrations after loading the structure.
Accomplishing this requires more involved database interactions (multiple additional queries to the database after `pg_dump` completes), so switch to testing using a real database. Include a basic `docker-compose.yml` as the beginning of providing a standard environment for local testing too.
=> Append schema_migrations INSERT statement at end of structure dump

lib/hanami/cli/commands/gem/new.rb, lib/hanami/cli/errors.rb, lib/hanami/cli/generators/context.rb, lib/hanami/cli/generators/gem/app.rb, lib/hanami/cli/generators/gem/app/env.erb, lib/hanami/cli/generators/gem/app/gemfile.erb, lib/hanami/cli/generators/gem/app/gitignore.erb, lib/hanami/cli/generators/gem/app/operation.erb, lib/hanami/cli/generators/gem/app/relation.erb, lib/hanami/cli/generators/gem/app/repo.erb, lib/hanami/cli/generators/gem/app/struct.erb, spec/unit/hanami/cli/commands/gem/new_spec.rb
Resolves #147.
A couple things.
1. I didn't add any `DATABASE_URL` to `.env` yet. I like the pattern of putting those into `.env.development` and `.env.test`. I know there was some discussion about an automatic translation from a development DATABASE_URL to a test one but not sure where we landed on that. When deploying to production, it's a feature that it won't deploy without DATABASE_URL set on the production server, so the development one isn't used accidentally.
2. I added some constants without `private_constant` so I can re-use them. I don't really like where they are now, any ideas of a better place to put them?
3. I removed passing along the rest of the kwargs to the context, due to some syntax errors on 3.0 and 3.1 since I broke up the method calls (I think). Not sure if this is …
=> Generate db files during hanami new

lib/hanami/cli/generators/gem/app.rb, spec/unit/hanami/cli/commands/gem/new_spec.rb
Clean up for #180. I realized I missed adding `app/relations/.keep`, so this does that. 
I also:
- moved around some expectations so they're grouped logically with their base class
- added a missing expectation for `app/actions/.keep`
- changed how `app/repos/.keep` and `app/structs/.keep` are generated so their creation message is printed
Fixes #190, fixes #191
=> Add .keep file for app/relations, reorder expectations

lib/hanami/cli/generators/app/action_context.rb, lib/hanami/cli/generators/app/component_context.rb, lib/hanami/cli/generators/app/operation_context.rb, lib/hanami/cli/generators/app/part_context.rb, lib/hanami/cli/generators/app/slice_context.rb, lib/hanami/cli/generators/app/view_context.rb, lib/hanami/cli/generators/constants.rb
Based on https://github.com/hanami/cli/pull/130#discussion_r1627648954 I moved the constants commonly used in all generators to a common place. This also required a simple change to one of the context classes, as it was using OFFSET that was an integer, instead of the one that is an alias to INDENTATION and work better with multiplication in the code that generates the spacing in end files.
=> Move constants used in generators

Gemfile, lib/hanami/cli/commands/app/db/command.rb, lib/hanami/cli/commands/app/db/migrate.rb, lib/hanami/cli/commands/app/generate/action.rb, lib/hanami/cli/commands/app/generate/part.rb, lib/hanami/cli/commands/app/install.rb, lib/hanami/cli/commands/app/middleware.rb, lib/hanami/cli/commands/app/server.rb, lib/hanami/cli/commands/gem/new.rb
I saw a bunch of `--[no]-skip-view` etc, which doesn't make sense. I realized it's because we're using `type: :boolean` instead of `type: :flag`.
I went though each one and I think they can all be converted to flags without losing anything, so that's what I did here.
This **does not currently work** so should not be merged, but it should work once https://github.com/dry-rb/dry-cli/pull/117 is brought up-to-date and merged. I'll handle fixing that up tomorrow, and change this PR to a non-draft once that's merged.
=> Use dry-cli's :flag type instead of :boolean

lib/hanami/cli/commands/app/generate/command.rb, lib/hanami/cli/commands/app/generate/migration.rb, lib/hanami/cli/commands/app/generate/operation.rb, lib/hanami/cli/commands/app/generate/relation.rb, lib/hanami/cli/commands/app/generate/repo.rb, lib/hanami/cli/commands/app/generate/struct.rb
Our recently updated `generate` subcommands are using a new `Commands::App::Generate::Command` base class, which had `argument :name` defined.
However, many of these subclasses _also_ had their own `argument :name` defined too, which led to these commands expecting _two_ name arguments to be given, which is incorrect.
I've fixed this by removing the `argument :name` from the base class, since having this in the subclasses allows them to provide their own specific `desc:` help text. After this change, commands like `generate relation create_posts` work again.
=> Fix redundant name arg in generate commands

README.md, docker-compose.yml, lib/hanami/cli/commands/app/db/command.rb, lib/hanami/cli/commands/app/db/migrate.rb, spec/support/postgres.rb, spec/unit/hanami/cli/commands/app/db/migrate_spec.rb
Came to fix one thing and found a few more :)
1. Fix the docker-compose configuration: use correct port, provide the password, add a note to the readme about `docker compose up` (successor to docker-compose)
2. Re-word the warning when the user is missing `config/db/`. I found this from upgrading to 2.2.0.beta1 and the message I got was `WARNING: Database ./db/bookshelf_development.sqlite has no config/db/ directory` which doesn't make a ton of sense. Now it'll say `WARNING: Database ./db/bookshelf_development.sqlite expects the folder config/db/ to exist but it does not.`
3. Add a specific warning when the user is missing `config/db/migrate/` (but has `config/db`)
4. Add a specific warning when the user has `config/db/migrate/` but it's empty (they might _have_ this folder but then have …
=> Improve db/migrations misconfigurations

.github/workflows/ci.yml, Gemfile, docker-compose.yml, lib/hanami/cli/commands/app/db/utils/database.rb, lib/hanami/cli/commands/app/db/utils/mysql.rb, lib/hanami/cli/commands/app/db/utils/postgres.rb, lib/hanami/cli/generators/context.rb, spec/spec_helper.rb, spec/support/mysql.rb, spec/support/postgres.rb, spec/unit/hanami/cli/commands/app/db/create_spec.rb, spec/unit/hanami/cli/commands/app/db/drop_spec.rb, spec/unit/hanami/cli/commands/app/db/structure/dump_spec.rb, spec/unit/hanami/cli/commands/app/db/structure/load_spec.rb, spec/unit/hanami/cli/commands/gem/new_spec.rb
Make `Hanami::CLI::Commands::App::DB::Utils::Mysql` a working implementation, so that MySQL databases can be used for the `db create`, `db drop`, `db structure dump` and `db structure load` commands.
In new apps generated with the `--database mysql` option, generate `mysql2://` database URLs, since this is the URL scheme required to connect using the mysql2 gem with Sequel (which underpins rom-sql).
Add a working MySQL database and support code for testing.
Resolves #157
=> Add MySQL support for `db` commands

lib/hanami/cli/command.rb, lib/hanami/cli/files.rb, spec/unit/hanami/cli/commands/app/generate/relation_spec.rb
(re-opened with correct commit history)
closes [#209 ](https://github.com/hanami/cli/issues/209)
I took @cllns  's advice and implemented this in `Hanami::CLI::Files#write`
Had to take care to skip this behavior when running hanami new, or else we'd never "keep" ( 😏 ) the files to begin with! Let me know if there are any suggestions on improvements
Thanks!
=> Deleting .keep files using the generators

lib/hanami/cli/commands/app/generate/command.rb, lib/hanami/cli/commands/app/generate/relation.rb, lib/hanami/cli/commands/app/generate/repo.rb, lib/hanami/cli/generators/app/migration.rb, lib/hanami/cli/generators/app/operation.rb, lib/hanami/cli/generators/app/relation.rb, lib/hanami/cli/generators/app/repo.rb, lib/hanami/cli/generators/app/ruby_file_writer.rb, lib/hanami/cli/generators/app/struct.rb
Addresses #202
Although, I ended up not using `slice.source_path`. I had an implementation working that just took a `Hanami::Slice` and used `.namespace` and `.source_path` but it proved hard to test. I couldn't figure out how to register a slice into the `Test::App`. 
Instead, the RubyFileWriter takes `namespace` and `base_path`, and we do the mapping in `Generate::Command`.
Happy to change this over if we can figure out a simple way to test that, to simplify the code, but I also feel like it's reasonable that a "File Writer" would require a namespace and a path as separate args, even though they're coupled in our apps.
I also changed the RubyFileWriter implementation so that `call` takes the file-specific args, instead of no args for `call` and all of them being passed to the …
=> Refactor RubyFileWriter

.rubocop.yml, Gemfile, lib/hanami/cli/commands/app/db/command.rb, lib/hanami/cli/commands/app/db/create.rb, lib/hanami/cli/commands/app/db/drop.rb, lib/hanami/cli/commands/app/db/migrate.rb, lib/hanami/cli/commands/app/db/structure/dump.rb, lib/hanami/cli/commands/app/db/structure/load.rb, lib/hanami/cli/commands/app/db/utils/database.rb, lib/hanami/cli/commands/app/db/version.rb, lib/hanami/cli/commands/app/generate/migration.rb, lib/hanami/cli/generators/app/migration.rb, spec/spec_helper.rb, spec/unit/hanami/cli/commands/app/db/create_spec.rb, spec/unit/hanami/cli/commands/app/db/drop_spec.rb, spec/unit/hanami/cli/commands/app/db/migrate_spec.rb, spec/unit/hanami/cli/commands/app/db/structure/dump_spec.rb, spec/unit/hanami/cli/commands/app/db/structure/load_spec.rb, spec/unit/hanami/cli/commands/app/db/version_spec.rb, spec/unit/hanami/cli/commands/app/generate/migration_spec.rb
Update the CLI for the DB gateway support introduced in https://github.com/hanami/hanami/pull/1452:
Add `--gateway` option to the following CLI commands:
- `db structure dump`
- `db structure load`
- `db create`
- `db drop`
- `db migrate`
- `db version`
- `generate migration`
These commands will operate on an individual gateway when the `--gateway` is given. Otherwise, they will operate on all the gateways for a given app or slice (or the app and all slices) based on the other args given, as before.
The above commands work with the following new file structures:
- Migrations for gateways in `config/db/[gateway_name]_migrate/` directories
- Structure files for gateways at `config/db/[gateway_name]_structure.sql`
The `db prepare` and `db seed` commands do _not_ support a `--gateway` option. …
=> Update DB commands to support multiple gateways per slice

lib/hanami/cli/generators/app/migration.rb
When a `""` base path element (which we use for app migrations) is given to `fs.join`, it will convert it into a leading `/`, which means we were attempting to write a migration into the root of the filesystem, instead of into the current working directory (i.e. the root of the app).
=> Fix issue trying to generate migration at /

lib/hanami/cli/commands/app/db/command.rb, lib/hanami/cli/commands/app/db/migrate.rb, lib/hanami/cli/commands/app/db/prepare.rb, lib/hanami/cli/commands/app/db/seed.rb, lib/hanami/cli/commands/app/db/utils/database.rb, spec/unit/hanami/cli/commands/app/db/prepare_spec.rb
Fix a range of issues detected during manual testing with a (soon-to-be) 2.2.beta2 app with multiple DB gateways configured for the app:
- `db prepare` was failing, since the ROM/Sequel migrator needs every configured getaway to have its database created before the migrator can run. To fix this, change the order of the nested `db prepare` commands, so that `db create` and `db structure load` are run first for _every_ detected database. After that is done, move onto `db migrate` for each detected database. Finally, run `db seed`.
- Given that `db prepare` now runs commands in a mixed order (i.e. no longer a single slice at a time), change the handling of command failures such that they halt and exit the entire command immediately. This should make it easier for the user to identify and …
=> Tweak db prepare/migrate/seed for multiple gateways

lib/hanami/cli/commands/app/db/command.rb, lib/hanami/cli/commands/app/db/utils/database.rb, spec/unit/hanami/cli/commands/app/db/drop_spec.rb
Fix bug introduced with the multiple gateway support where the `db` commands, when called without the `--app` or `--slice` args (i.e. commands intended to find all databases in the app), would operate multiple times on the same databases within a slice with >1 gateway.
=> Fix db commands acting on same databases multiple times

lib/hanami/cli/commands/app/generate/action.rb, lib/hanami/cli/commands/app/generate/slice.rb, lib/hanami/cli/generators/app/action.rb, lib/hanami/cli/generators/app/slice.rb, lib/hanami/cli/generators/app/slice_context.rb, spec/unit/hanami/cli/commands/app/generate/action_spec.rb, spec/unit/hanami/cli/commands/app/generate/slice_spec.rb
closes [#196](https://github.com/hanami/cli/issues/196)
i tried to mirror the existing implementation of the other flags, even if we ended up with goofy functions like `Generators::App::Action#generate_route?`
lmk if you'd like to see any changes, thanks!
=> Add --skip-route flag for action and slice generators

lib/hanami/cli/commands/app/db/structure/dump.rb, lib/hanami/cli/commands/app/db/utils/postgres.rb
Address the error attmpting to implicitly convert nil into a string.
While here, avoid appending spurious newlines to the structure file when there are no migrations.
Fixes #239
=> Fix error dumping structure when no migrations

lib/hanami/cli/commands/app/db/utils/postgres.rb
Now that the `db` CLI commands support multiple gateways, we need to use the relevant gateway when preparing this line of SQL.
=> Use relevant gateway for fetching search_path

lib/hanami/cli/commands/app/command.rb
This allows app commands to be invoked with e.g. `-e test` instead of being prepended with `HANAMI_ENV=test`, which is awkward.
This change simply adds the `option` declaration to register the `:env` option with the command classes. The handling of the `env:` argument was already in place.
Resolves #214
=> Add `--env` (or `-e`) option to all app commands

lib/hanami/cli/commands/app/db/command.rb, lib/hanami/cli/commands/app/db/create.rb, lib/hanami/cli/commands/app/db/drop.rb, lib/hanami/cli/commands/app/db/migrate.rb, lib/hanami/cli/commands/app/db/prepare.rb, lib/hanami/cli/commands/app/db/structure/load.rb, spec/support/hanami_cli_environment.rb, spec/unit/hanami/cli/commands/app/db/create_spec.rb, spec/unit/hanami/cli/commands/app/db/drop_spec.rb, spec/unit/hanami/cli/commands/app/db/migrate_spec.rb, spec/unit/hanami/cli/commands/app/db/prepare_spec.rb, spec/unit/hanami/cli/commands/app/db/structure/load_spec.rb
It's a frustrating experience if users have to remember to run each of their `hanami db` commands again with `-e test` after running them on their development database.
To improve this, update a number of commands to automatically re-run on the test database after completing their work on the development database:
- `db create`
- `db drop`
- `db migrate`
- `db prepare`
- `db structure load`
The re-run on test will only take place if these commands operate with the development environment. Running the commands in other environments (e.g. production or test) will run on the database in those environments **only.**
To achieve this "re-run on test" behaviour, at the end of these `db` commands, we invoke another process to call the relevant `hanami db` command again, but with the …
=> Run db commands on test as well as development databases

lib/hanami/cli/generators/context.rb, spec/unit/hanami/cli/commands/gem/new_spec.rb
Specify the root user, which is required to connect to MySQL as installed by homebrew.
Resolves #248
=> Make default MySQL database URL work with Homebrew

lib/hanami/cli/generators/gem/app/operation.erb, spec/unit/hanami/cli/commands/gem/new_spec.rb
Now that https://github.com/hanami/hanami/pull/1456 is merged and the ROM extension is automatically included in operations inside Hanami apps, we no longer need to generate the boilerplate.
=> Remove boilerplate from generated app operation

lib/hanami/cli/commands/app/db/command.rb, spec/unit/hanami/cli/commands/app/db/migrate_spec.rb
Fix a bug where the misconfigured db warning was printing whenever two slices shared a database URL (regardless of whether they had config). Also take into consideration the new gateway-specific migration dirs, and print a warning if there are multiple config dirs for a gateway.
=> Fix misconfigured db warnings, include gateways

lib/hanami/cli/commands/app/console.rb
The existing code would fallback to "pry" as it is the first element of the ENGINES constant. This commit makes it fallback to the engined described on the DEFAULT_ENGINE variable
PS: I also noticed that the "reload" method doesn't consider the `--engine=something`, [here](https://github.com/hanami/cli/blob/07b8c55790d8f5e8d21bdce8caba02f418cae768/lib/hanami/console/context.rb#L39)
but I'm not sure how to fix this one
=> [Fix] Console default engine

lib/hanami/cli/repl/irb.rb
Don’t add an extra space when the prompt enters its PROMPT_S (continued strings) and PROMPT_C (continued statements) modes.
=> Stop IRB prompt from shifting width

lib/hanami/cli/commands/app/generate/component.rb, lib/hanami/cli/generators/app/component.rb
The component generator was created before the operation generator. It's potentially confusing to generate a component called "operation", since we have an operation generator.
~I don't think services is a terrific alternative (since it's often used in the same way as operation) so please let me know if anyone has any better ideas. Just wanted to open this so I don't forget~
I brainstormed some domain-specific components someone could want for a bookshelf app. Open to other suggestions (in particular ISBN should be an acronym, but it's not in the default inflector, so I think it's find to render it as `Isbn`, but it's not ideal)
=> Change component generator examples to domain-specific ones

lib/hanami/cli/generators/gem/app/gemfile.erb, spec/unit/hanami/cli/commands/gem/new_spec.rb
Now that 1.7 is out, we can get away with just a single version constraint, rather than two.
=> Simplify dry-types version constraint in Gemfile

lib/hanami/cli/generators/app/migration.rb, spec/unit/hanami/cli/commands/app/generate/migration_spec.rb
There's an official location for Hanami docs now, it does ultimately link back to Sequel's docs but those have a bunch of extraneous information that isn't pertinent for a Hanami project.
=> Update migration link to point to Hanami website

lib/hanami/cli/commands/gem/new.rb, spec/unit/hanami/cli/commands/gem/new_spec.rb
Raising a conflicting options error when both are given is a problem, because we _default_ the `database` option to be “sqlite”, which means it’s impossible for the user to un-set.
Instead or raising an error, simply allow `—skip-db` to take priority when given. This means if it is given together with `--database`, the `--database` option will be ignored.
Fixes #267
=> Allow --skip-db and --database to be given, preferring --skip-db

lib/hanami/cli/commands/app/install.rb, lib/hanami/cli/commands/gem/new.rb, spec/unit/hanami/cli/commands/app/install_spec.rb, spec/unit/hanami/cli/commands/gem/new_spec.rb
This will ensure that gems added to the `Gemfile` by our first-party extensions (hanami-cli) are installed during `hanami new`, rather than requiring the user to run their own manual `bundle install` afterwards.
This requires the first-party extension gems to use a `before "install"` command hook, instead of the current `after "install"`.
See also https://github.com/hanami/rspec/pull/30
Fixes #265
=> Bundle install during hanami install

hanami-cli.gemspec
`irb` will be a bundled gem from Ruby 3.5.
https://bugs.ruby-lang.org/issues/20309
So if we use `irb` as the standard library, Bundler shows the following warning.
```
lib/ruby/gems/3.4.0/gems/hanami-cli-2.2.1/lib/hanami/cli/repl/irb.rb:3: warning: irb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
```
This PR adds the `irb` to a runtime dependency to fix the warning.
=> Add `irb`gem as a runtime dependency

lib/hanami/cli/generators/gem/app/gitignore.erb, spec/unit/hanami/cli/commands/gem/new_spec.rb
Closes [#285](https://github.com/hanami/cli/issues/285)
When generating the .gitignore file on `hanami new`, allow the `public/404.html` and `public/500.html` files, while keeping the rest of `public/` ignored.
please let me know if you'd like to see any changes. thanks!
-----
reopening after unintentionally closing [#286](https://github.com/hanami/cli/pull/286)
=> Allow source control of public/404,500.html via gitignore

CHANGELOG.md, lib/hanami/cli/generators/gem/app/assets.js, spec/unit/hanami/cli/commands/gem/new_spec.rb
Previously, there was a line that was just `await assets.run()` that was not commented, and a commented block that was suggested for customization. As a result, it was possible that the initial line would be left when enabling the block, which causes a double-build and can also cause a lot of confusion once some customization is added. 
Given that the default customization function doesn't do anything, the computational cost of just executing it seems acceptable to simplify the setup and reduce the chance of frustration.
(I know this because I ran into this issue while adding Tailwind and PostCSS, and wound up being confused why builds were failing to find Tailwind. Real PEBKAC, but I hope that this would help save someone else the grief. I also expanded the comments on the file to try …
=> Clarify customizability of config/assets.js

lib/hanami/cli/commands/gem/new.rb, spec/unit/hanami/cli/commands/gem/new_spec.rb
Adding simple git repo initialization, with similar code to npm install (as for handling error display). Running it after the main install command
=> Add simple git init at the end of new hanami app command

lib/hanami/cli/commands/app/db/utils/mysql.rb, lib/hanami/cli/commands/app/db/utils/postgres.rb, lib/hanami/cli/errors.rb, spec/unit/hanami/cli/commands/app/db/drop_spec.rb
Currently if the existence check for a database fails (for example due to whole database server being down or user not existing), Hanami CLI will anyway return information that the database was dropped.
This changes it to failing with an explicit error message in such case. Examples:
```
$ hanami db drop
Could not check if the database exists. Error message:
psql: error: connection to server at "localhost" (::1), port 5432 failed: Connection refused
Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
Is the server running on that host and accepting TCP/IP connections?
```
```
$ hanami db drop
Could not check if the database exists. Error message:
psql: error: connection to server at …
```
=> Fail `hanami db drop` when cannot check database existence

lib/hanami/cli/commands/gem/new.rb, lib/hanami/cli/generators/context.rb, lib/hanami/cli/generators/gem/app.rb, lib/hanami/cli/generators/gem/app/gemfile.erb, spec/unit/hanami/cli/commands/gem/new_spec.rb
closes #301 
This PR adds an optional `--skip-view` flag to the `hanami new` command. including this flag will not bundle the `hanami-view` gem, and will not generate any of the initial view files or directories (e.g. the things in `app/views` and `app/templates`)
however, this _does_ still potentially allow assets files to be created.  the idea being if you wanted to skip views and assets you'd use `hanami new` in api mode (#302)
=> Add app level --skip-view flag

Gemfile, hanami-cli.gemspec, lib/hanami/cli/commands/app/server.rb, lib/hanami/cli/server.rb
updates to Rack 3. one part of many gem updates
[list of changes](https://github.com/hanami/router/pull/277)
adds rackup as an [explicit dependency](https://github.com/rack/rack/blob/main/UPGRADE-GUIDE.md#binrackup-rackserver-rackhandlerand--racklobster-were-moved-to-a-separate-gem)
----
bringing back a previously inadvertently closed [PR](https://github.com/hanami/cli/pull/283)
=> Add support for Rack 3

lib/hanami/cli/commands/app/generate/command.rb, lib/hanami/cli/generators/app/part.rb, spec/integration/hanami/cli/commands/app/generate/part_spec.rb
Clean up for #292. Right now `hanami generate part` (from hanami/cli main) is broken.
`skip_tests:` wasn't being accepted, so it was raising an ArgumentError (hanami-rspec looks at that option)
This also adds a regression test for that, plus allowing arbitrary kwargs args
=> Fix ArgumentError for Part generator

lib/hanami/cli/commands/app/db/utils/mysql.rb
As of MySQL 9.4, client commands are disabled by default for the `mysql` CLI (see https://dev.mysql.com/doc/relnotes/mysql/9.4/en/news-9-4-0.html). Pass the `-—commands` CLI arg to allow `db structure load` (which uses the MySQL `SOURCE` client command) to continue to work.
=> Ensure MySQL 9.4 compatibility for `db structure load` command

lib/hanami/cli/generators/gem/app/gemfile.erb, spec/unit/hanami/cli/commands/gem/new_spec.rb
Small bug fix tonight to fix when using `--head` on `hanami new app --head` to automatically include the cli gem to reduce friction if there's a bug fix in CLI from GitHub for the other versions also using GitHub.
Generated an app with the fix:
```
gem "hanami", github: "hanami/hanami", branch: "main"
gem "hanami-cli", github: "hanami/cli", branch: "main"
gem "hanami-assets", github: "hanami/assets", branch: "main"
gem "hanami-controller", github: "hanami/controller", branch: "main"
gem "hanami-db", github: "hanami/db", branch: "main"
gem "hanami-router", github: "hanami/router", branch: "main"
gem "hanami-validations", github: "hanami/validations", branch: "main"
gem "hanami-view", github: "hanami/view", branch: "main"
```
=> When using --head for new apps, include cli from main github
